### ISSUE TITLE
more than 15 rows in a line

### ISSUE THREAD

**Issue by naphystart** [miusuncle/HiveSprite#4]
It's an excellent script, it helps a lot in my work and I appreciate that. And I found out something strange when there are too many rows in a line, some pics will disappear in the generated sprite. Do you get any ideas about this?

**Comment by miusuncle** [comment]
You mean more than 15 columns in a line? There is no special handle for columns exceed whatever threshold. So it is really strange, maybe Photoshop cannot recognise some pics that you specified. You can isolate these pics to see if any difference among the others.

By the way, after I developed this script for my work, I found [HiveSpLite](https://github.com/miusuncle/HiveSpLite) meet my need much more.
